name: rain_clothes_app
description: "Automatic clothing rain protection system with ESP32 and weather forecast."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  geolocator: ^14.0.2
  dio: ^5.4.0
  riverpod: ^3.2.1
  fl_chart: ^1.2.0
  responsive_framework: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true